name = "IonCLI"
uuid = "7a67c3bc-365d-4399-aa69-e9a17770ea1f"
authors = ["Roger-luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.5.2"

[deps]
LocalRegistry = "89398ba2-070a-4b16-a995-9893c55d93cf"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
RegistryTools = "d1eb7eb1-105f-429d-abf5-b0f65cb9e2c4"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"

[compat]
LocalRegistry = "0.3"
GitHub = "5.1"
StringDistances = "0.8"
PkgTemplates = "0.7"
OrderedCollections = "1.3"
julia = "1.4"
RegistryTools = "1.5"
Comonicon = "0.6"
